# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: People
    url: people
    weight: 10
  - name: Publications
    url: publication
    weight: 20
  - name: Contact
    url: contact
    weight: 80
  - name: News
    url: news
    weight: 50
  - name: Research
    url: research
    weight: 30
  - name: Teaching
    url: teaching
    weight: 40
  - name: Service
    url: service
    weight: 70
  - name: Blog
    url: blog
    weight: 60
